language: generic

services:
  - docker
sudo: required

before_script:
  - make build-image

script:
  - make

before_deploy:
  - git config --local user.name "Alexandre Carlton"
  - git config --local user.email "acar7163@uni.sydney.edu.au"
  - git remote set-url origin https://AlexandreCarlton:$GITHUB_TOKEN@github.com/AlexandreCarlton/arch-on-github.git
  - git tag -f latest
  # Delete the (previous) latest release, since Travis will not update the packages otherwise.
  - make delete-latest

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: repo/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: AlexandreCarlton/arch-on-github
